### PR TITLE
Daisydev

### PR DESCRIPTION
**Pull request by DaisyShi19**

### CODE REVIEW

**Comment by DaisyShi19** [comment]
@sunny-bak Hi Sunny, we wanted to create a folder for the ATN tutorials easier for people to download. Can you review pr and merge? Thank you.

**Comment by sunny-bak** [comment]
Hi Daisy,

I am on leave. Please feel free to merge if you think it makes sense!

Thanks,
Sunny

**Comment by DaisyShi19** [comment]
Hi Sunny, hope you're enjoying the time off :)
Can you give me access/authority to merge? Currently it says: 
Review required
At least 1 approving review is required by reviewers with write access. 
Merging is blocked
Merging can be performed automatically with 1 approving review

**Comment by sunny-bak** [comment]
The merge is blocked but as an administrator you should be able to continue
to merge.

I'm on the merge page now and want to check if you can still merge it
although it says it.

Could you try? If it doesn't work I will do it.

**Comment by DaisyShi19** [comment]
Thanks Sunny, and sorry I was away for a bit. I was able to merge early PRs but not this one. I was wondering if it has deleted files. Anyways, it should be good from now.

**Comment by sunny-bak** [comment]
Hi Daisy,


I merged it for you and also made you the admin of the repo.

I accidentally change the ownership of the total account to you. Can you go
and give me back the ownership? I can't access other repositores

**Comment by sunny-bak** [comment]
Go to the account coastwatch-training and go to people and click shospital
and made me the owner.

Mahalo

**Comment by sunny-bak** [comment]
Now you are the administrator of the coastwach tutorial repo and you can
bypass the review process to merge.

**Comment by DaisyShi19** [comment]
Changed. Can you check if it it correctly done?

**Comment by DaisyShi19** [comment]
Thank you Sunny. I'll only need it till the end of Nov when trainings are
done. And thank you again for helping out while on leave!

**Comment by sunny-bak** [comment]
Yes. Sorry I was still an owner. We can have one or more owners. Now you
and i are owners.

**Comment by DaisyShi19** [comment]
OK sounds good!

**Pull request merged**
