### PR TITLE
fixed minor typo

### PR DESCRIPTION
**Pull request by DaisyShi19**

### CODE REVIEW

**Comment by DaisyShi19** [comment]
Sorry to pin you again Sunny, it doesn't seem to let me merge. Can you double-check the settings? Thanks! @sunny-bak

**Comment by sunny-bak** [comment]
I checked and you are the owner of the account and admin of the repo.

Did you create PR and try to merge? What does the error say?

**Comment by DaisyShi19** [comment]
Review required
At least 1 approving review is required by reviewers with write access. 
1 pending reviewer

Merging is blocked
Merging can be performed automatically with 1 approving review.
  Merge without waiting for requirements to be met (bypass branch protections)

**Comment by DaisyShi19** [comment]
It's so strange. I was to be able to merge for the workshop page. Perhaps the two repo have different settings?

**Comment by sunny-bak** [comment]
Do you not see the check box for merging without waiting for the
requirement...? Once you check it, you should be able to merge.

**Comment by sunny-bak** [comment]
I set it up that way on purpose because tutorial materials are more complex
with more collbaorators so i wanted someone to review before merging to
prevent any errors.

**Comment by DaisyShi19** [comment]
Ah I see, ok, got it! Thanks again Sunny!

**Comment by sunny-bak** [comment]
Good job!

**Pull request merged**
